apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo-app

spec:
  containers:
  - name: demo-nginx
    image: nginx
    ports:
      - name: demo-nginx
        containerPort: 80
